config/routes.rb
Rails.application.routes.draw do
  resources :translation_words

  resources :words

  resources :locales

  resources :dictionaries

  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  has_many :word
end

app/models/locale.rb
class Locale < ActiveRecord::Base
end

app/models/translation_word.rb
class TranslationWord < ActiveRecord::Base
  belongs_to :work
  belongs_to :locale
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :dictionary
  has_many :translation_word
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @dictionaries = Dictionary.all
    respond_with(@dictionaries)
  end

  def show
    respond_with(@dictionary)
  end

  def new
    @dictionary = Dictionary.new
    respond_with(@dictionary)
  end

  def edit
  end

  def create
    @dictionary = Dictionary.new(dictionary_params)
    flash[:notice] = 'Dictionary was successfully created.' if @dictionary.save
    respond_with(@dictionary)
  end

  def update
    flash[:notice] = 'Dictionary was successfully updated.' if @dictionary.update(dictionary_params)
    respond_with(@dictionary)
  end

  def destroy
    @dictionary.destroy
    respond_with(@dictionary)
  end

  private
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    def dictionary_params
      params.require(:dictionary).permit(:name, :description)
    end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
  before_action :set_locale, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @locales = Locale.all
    respond_with(@locales)
  end

  def show
    respond_with(@locale)
  end

  def new
    @locale = Locale.new
    respond_with(@locale)
  end

  def edit
  end

  def create
    @locale = Locale.new(locale_params)
    @locale.save
    respond_with(@locale)
  end

  def update
    @locale.update(locale_params)
    respond_with(@locale)
  end

  def destroy
    @locale.destroy
    respond_with(@locale)
  end

  private
    def set_locale
      @locale = Locale.find(params[:id])
    end

    def locale_params
      params.require(:locale).permit(:lang_territory)
    end
end

app/controllers/translation_words_controller.rb
class TranslationWordsController < ApplicationController
  before_action :set_translation_word, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @translation_words = TranslationWord.all
    respond_with(@translation_words)
  end

  def show
    respond_with(@translation_word)
  end

  def new
    @translation_word = TranslationWord.new
    respond_with(@translation_word)
  end

  def edit
  end

  def create
    @translation_word = TranslationWord.new(translation_word_params)
    @translation_word.save
    respond_with(@translation_word)
  end

  def update
    @translation_word.update(translation_word_params)
    respond_with(@translation_word)
  end

  def destroy
    @translation_word.destroy
    respond_with(@translation_word)
  end

  private
    def set_translation_word
      @translation_word = TranslationWord.find(params[:id])
    end

    def translation_word_params
      params.require(:translation_word).permit(:prev_id, :cud_type, :work_id, :locale_id, :content, :progress_status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @words = Word.all
    respond_with(@words)
  end

  def show
    respond_with(@word)
  end

  def new
    @word = Word.new
    respond_with(@word)
  end

  def edit
  end

  def create
    @word = Word.new(word_params)
    @word.save
    respond_with(@word)
  end

  def update
    @word.update(word_params)
    respond_with(@word)
  end

  def destroy
    @word.destroy
    respond_with(@word)
  end

  private
    def set_word
      @word = Word.find(params[:id])
    end

    def word_params
      params.require(:word).permit(:dictionary_id, :use_status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/translation_words_helper.rb
module TranslationWordsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/dictionaries/_form.html.erb
<%= form_for(@dictionary, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @dictionary.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@dictionary.errors.count, "error") %> prohibited this dictionary from being saved:</h4>

      <ul>
      <% @dictionary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/dictionaries/edit.html.erb
<div class="page-header">
  <%= link_to dictionaries_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @dictionary, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing dictionary</h1>
</div>

<%= render 'form' %>

app/views/dictionaries/index.html.erb
<div class="page-header">
  <%= link_to new_dictionary_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Dictionary
  <% end %>
  <h1>Listing dictionaries</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @dictionaries) do |dictionary| %>
            <td><%= dictionary.name %></td>
            <td><%= dictionary.description %></td>
            <td><%= link_to 'Show', dictionary %></td>
        <td><%= link_to 'Edit', edit_dictionary_path(dictionary) %></td>
        <td><%= link_to 'Destroy', dictionary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dictionaries/new.html.erb
<div class="page-header">
  <%= link_to dictionaries_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New dictionary</h1>
</div>

<%= render 'form' %>

app/views/dictionaries/show.html.erb
<div class="page-header">
  <%= link_to dictionaries_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_dictionary_path(@dictionary), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show dictionary</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @dictionary.name %></dd>

  <dt>Description:</dt>
  <dd><%= @dictionary.description %></dd>

</dl>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="">
  <title><%= content_for?(:title) ? yield(:title) : "Translation Ms" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Translation Ms" %>">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="tmsApp">
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <main role="main">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </main>
</body>
</html>

app/views/locales/_form.html.erb
<%= form_for(@locale, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @locale.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@locale.errors.count, "error") %> prohibited this locale from being saved:</h4>

      <ul>
      <% @locale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :lang_territory, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lang_territory, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/locales/edit.html.erb
<div class="page-header">
  <%= link_to locales_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @locale, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing locale</h1>
</div>

<%= render 'form' %>

app/views/locales/index.html.erb
<div class="page-header">
  <%= link_to new_locale_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Locale
  <% end %>
  <h1>Listing locales</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Lang territory</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @locales) do |locale| %>
            <td><%= locale.lang_territory %></td>
            <td><%= link_to 'Show', locale %></td>
        <td><%= link_to 'Edit', edit_locale_path(locale) %></td>
        <td><%= link_to 'Destroy', locale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/locales/new.html.erb
<div class="page-header">
  <%= link_to locales_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New locale</h1>
</div>

<%= render 'form' %>

app/views/locales/show.html.erb
<div class="page-header">
  <%= link_to locales_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_locale_path(@locale), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show locale</h1>
</div>

<dl class="dl-horizontal">
  <dt>Lang territory:</dt>
  <dd><%= @locale.lang_territory %></dd>

</dl>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/translation_words/_form.html.erb
<%= form_for(@translation_word, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @translation_word.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@translation_word.errors.count, "error") %> prohibited this translation_word from being saved:</h4>

      <ul>
      <% @translation_word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :prev_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :prev_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cud_type, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cud_type, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :work, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :work, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :locale, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :locale, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :content, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :progress_status, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :progress_status, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/translation_words/edit.html.erb
<div class="page-header">
  <%= link_to translation_words_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @translation_word, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing translation_word</h1>
</div>

<%= render 'form' %>

app/views/translation_words/index.html.erb
<div class="page-header">
  <%= link_to new_translation_word_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Translation word
  <% end %>
  <h1>Listing translation_words</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Prev</th>
            <th>Cud type</th>
            <th>Work</th>
            <th>Locale</th>
            <th>Content</th>
            <th>Progress status</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @translation_words) do |translation_word| %>
            <td><%= translation_word.prev_id %></td>
            <td><%= translation_word.cud_type %></td>
            <td><%= translation_word.work %></td>
            <td><%= translation_word.locale %></td>
            <td><%= translation_word.content %></td>
            <td><%= translation_word.progress_status %></td>
            <td><%= link_to 'Show', translation_word %></td>
        <td><%= link_to 'Edit', edit_translation_word_path(translation_word) %></td>
        <td><%= link_to 'Destroy', translation_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/translation_words/new.html.erb
<div class="page-header">
  <%= link_to translation_words_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New translation_word</h1>
</div>

<%= render 'form' %>

app/views/translation_words/show.html.erb
<div class="page-header">
  <%= link_to translation_words_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_translation_word_path(@translation_word), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show translation_word</h1>
</div>

<dl class="dl-horizontal">
  <dt>Prev:</dt>
  <dd><%= @translation_word.prev_id %></dd>

  <dt>Cud type:</dt>
  <dd><%= @translation_word.cud_type %></dd>

  <dt>Work:</dt>
  <dd><%= @translation_word.work %></dd>

  <dt>Locale:</dt>
  <dd><%= @translation_word.locale %></dd>

  <dt>Content:</dt>
  <dd><%= @translation_word.content %></dd>

  <dt>Progress status:</dt>
  <dd><%= @translation_word.progress_status %></dd>

</dl>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

app/views/words/_form.html.erb
<%= form_for(@word, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @word.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h4>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :dictionary, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :dictionary, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :use_status, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :use_status, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/words/edit.html.erb
<div class="page-header">
  <%= link_to words_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @word, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing word</h1>
</div>

<%= render 'form' %>

app/views/words/index.html.erb
<div class="page-header">
  <%= link_to new_word_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Word
  <% end %>
  <h1>Listing words</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Dictionary</th>
            <th>Use status</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @words) do |word| %>
            <td><%= word.dictionary %></td>
            <td><%= word.use_status %></td>
            <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/words/new.html.erb
<div class="page-header">
  <%= link_to words_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New word</h1>
</div>

<%= render 'form' %>

app/views/words/show.html.erb
<div class="page-header">
  <%= link_to words_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_word_path(@word), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show word</h1>
</div>

<dl class="dl-horizontal">
  <dt>Dictionary:</dt>
  <dd><%= @word.dictionary %></dd>

  <dt>Use status:</dt>
  <dd><%= @word.use_status %></dd>

</dl>